"""Turn a Garmin workout into workouts.yaml content.

Garmin knows less than this tool needs. It stores one target per exercise, not
a range, and has no concept of a weight step or of counting a lunge per side.
So an import fills in everything that can be read from the payload, guesses the
load type from the exercise name, and marks the rest for the user to decide.

Pure: takes payloads, returns text. Nothing here talks to Garmin.
"""

from __future__ import annotations

from dataclasses import dataclass

from .garmin.payloads import iter_exercise_blocks, step_target

#: How many reps above the imported target to suggest as the top of the range.
REP_RANGE_WIDTH = 4
#: The same, for timed holds, in seconds.
TIME_RANGE_WIDTH = 15

#: Substrings that identify a load type, most specific first.
_LOAD_HINTS = (
    ("BARBELL", "barbell"),
    ("DUMBBELL", "dumbbell"),
    ("CABLE", "cable"),
    ("MACHINE", "machine"),
    ("SMITH", "machine"),
)


@dataclass(frozen=True)
class ImportedExercise:
    """One exercise as read out of Garmin, plus what had to be guessed."""

    name: str
    garmin_name: str
    garmin_category: str | None
    sets: int
    rest: int | None
    rep_low: int
    rep_high: int
    load: str
    unit: str
    guessed_load: bool

    @property
    def time_based(self) -> bool:
        return self.unit == "seconds"


@dataclass(frozen=True)
class ImportedWorkout:
    """One Garmin workout, ready to be written out as config."""

    key: str
    garmin_workout_id: str
    activity_prefixes: list[str]
    exercises: list[ImportedExercise]


def humanise(garmin_name: str) -> str:
    """BARBELL_BACK_SQUAT -> Barbell Back Squat."""
    return " ".join(part.capitalize() for part in garmin_name.split("_") if part)


def guess_load(garmin_name: str, weight: float | None) -> tuple[str, bool]:
    """Best guess at the load type, and whether it was a guess at all.

    Garmin does not record how an exercise is loaded, so the name is the only
    signal. Anything unrecognised with a weight is called a machine, which is
    the least wrong default: it at least progresses.
    """
    upper = garmin_name.upper()
    for hint, load in _LOAD_HINTS:
        if hint in upper:
            return load, True
    if not weight:
        return "bodyweight", True
    return "machine", True


def describe_workout(payload: dict) -> ImportedWorkout:
    """Read a Garmin workout definition into importable form."""
    name = payload.get("workoutName") or "Unnamed workout"

    exercises: list[ImportedExercise] = []
    for block in iter_exercise_blocks(payload):
        garmin_name = block.step.get("exerciseName")
        category = block.step.get("category")
        # Either identifies the exercise; a step carrying neither is not one.
        label = garmin_name or category
        if not label:
            continue

        condition = (block.step.get("endCondition") or {}).get("conditionTypeKey")
        time_based = condition == "time"
        target = step_target(block.step, time_based)
        if target is None:
            continue  # a step with no target of its own, e.g. a lap.button hold

        load, guessed = guess_load(label, target.weight)
        width = TIME_RANGE_WIDTH if time_based else REP_RANGE_WIDTH

        exercises.append(
            ImportedExercise(
                name=humanise(label),
                garmin_name=label,
                garmin_category=category,
                sets=block.sets,
                rest=block.rest,
                # Garmin has a single target, so it becomes the bottom of the
                # range and the top is a suggestion.
                rep_low=target.reps,
                rep_high=target.reps + width,
                load=load,
                unit="seconds" if time_based else "reps",
                guessed_load=guessed,
            )
        )

    return ImportedWorkout(
        key=name,
        garmin_workout_id=str(payload.get("workoutId") or ""),
        activity_prefixes=[name.lower()],
        exercises=exercises,
    )


# --- rendering -------------------------------------------------------------

HEADER = """\
# Generated by `workout import`. Check the values marked TODO before relying on
# it: Garmin stores a single target rather than a rep range, and records no
# load type, so those had to be inferred.

settings:
  garmin:
    token_store: ~/.garminconnect
    activity_search_limit: 25
    dump_dir: .

  weight_steps:
    barbell: 2.5
    dumbbell: 1.0
    cable: 5.0
    machine: 5.0

workouts:
"""


def render_exercise(exercise: ImportedExercise) -> list[str]:
    unit = "s" if exercise.time_based else "reps"
    lines = [
        f"      - name: {exercise.name}",
        f"        garmin_name: {exercise.garmin_name}",
    ]
    if exercise.garmin_category:
        lines.append(f"        garmin_category: {exercise.garmin_category}")
    lines += [
        f"        rep_low: {exercise.rep_low}"
        f"    # Garmin's current target ({exercise.rep_low} {unit})",
        f"        rep_high: {exercise.rep_high}   # TODO: top of your range",
        f"        sets: {exercise.sets}",
    ]
    if exercise.rest is not None:
        lines.append(f"        rest: {exercise.rest}")
    suffix = (
        "   # TODO: guessed from the exercise name" if exercise.guessed_load else ""
    )
    lines.append(f"        load: {exercise.load}{suffix}")
    if exercise.time_based:
        lines.append("        unit: seconds")
    return lines


def render_workout(workout: ImportedWorkout) -> list[str]:
    prefixes = ", ".join(f'"{p}"' for p in workout.activity_prefixes)
    return [
        f"  - key: {workout.key}",
        f'    garmin_workout_id: "{workout.garmin_workout_id}"',
        f"    activity_prefixes: [{prefixes}]"
        "   # TODO: how your logged activities are named",
        "    exercises:",
        *[line for e in workout.exercises for line in render_exercise(e)],
    ]


def render_config(workouts: list[ImportedWorkout]) -> str:
    """A complete, valid workouts.yaml for the given workouts."""
    body: list[str] = []
    for workout in workouts:
        body.extend(render_workout(workout))
        body.append("")
    return HEADER + "\n".join(body).rstrip() + "\n"
